// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lmds
Rcpp::List lmds(arma::mat X, Rcpp::Nullable<arma::mat> X1_temp, int random_start, float k, float d, float lambda, float mu, float nu, float tau, int niter);
RcppExport SEXP _lmds_lmds(SEXP XSEXP, SEXP X1_tempSEXP, SEXP random_startSEXP, SEXP kSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP tauSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type X1_temp(X1_tempSEXP);
    Rcpp::traits::input_parameter< int >::type random_start(random_startSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    Rcpp::traits::input_parameter< float >::type d(dSEXP);
    Rcpp::traits::input_parameter< float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< float >::type mu(muSEXP);
    Rcpp::traits::input_parameter< float >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< float >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(lmds(X, X1_temp, random_start, k, d, lambda, mu, nu, tau, niter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lmds_lmds", (DL_FUNC) &_lmds_lmds, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_lmds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
