# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lmds <- function(X, X1_temp = NULL, random_start = 0L, k = 6.0, d = 2.0, lambda = 1.0, mu = 1.0, nu = 0.0, tau = 1.0, niter = 500L) {
    .Call('_lmds_lmds', PACKAGE = 'lmds', X, X1_temp, random_start, k, d, lambda, mu, nu, tau, niter)
}

